### ISSUE TITLE
【bug】触发路径链接配置失败，调用云函数超时或者失败

### ISSUE THREAD

**Issue by hermitlsr** [lmm214/bber-weixin#3]
不清楚这个代码木老师是否还在维护，冒昧提个 issue
我通过您的 [「哔哔点啥」微信公众号 2.0](https://immmmm.com/bb-by-wechat-pro/) 成功配置了bber，绑定您提供的微信也是成功的。

但是在配置 `bber-weixin` 时，出现了问题 ：

在教程第 2 步，触发路径链接 是无效的 即

```
https://bb-f5c0f-222222.ap-shanghai.app.tcloudbase.com/bber-weixin
```
在点击后会出现

```
请求ID: 42b81ea5189b3a6eed57a12eae6afc9f
错误码: INVOKE_FUNCTION_FAILED # 经查询，该错误为 调用云函数超时或者失败
错误信息: Code: 1 ScfRequestId: 6777521a-77c7-11ec-835c-525400534804 Error: Error [ERR_REQUIRE_ESM]: Must use import to load 
ES Module: /var/user/index.js require() of ES modules is not supported. require() of /var/user/index.js from /var/runtime/node12/UserFunction.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /var/user/package.json. at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13) at Module.load (internal/modules/cjs/loader.js:1002:32) at Function.Module._load (internal/modules/cjs/loader.js:901:14) at Module.require (internal/modules/cjs/loader.js:1044:19) at require (internal/modules/cjs/helpers.js:77:18) at Object.module.exports.load (/var/runtime/node12/UserFunction.js:26:19) at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:99:38) at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:56:12) at listOnTimeout (internal/timers.js:549:17) at processTimers (internal/timers.js:492:7)
```
经查询，该错误为 调用云函数超时或者失败
这个错误导致在后面的微信服务器配置中 token 是无法验证的，从而无法使用自己的公众号
希望木老师有时间可以看一下这个问题

**Comment by hermitlsr** [comment]
问题解决了，作者采用的运行环境 是 Nodejs10.15，而现在腾讯云开发默认的是 Nodejs12.16，如果采用前者则不会报错，如果使用后者也就是最新版，则需要将 package.json 中的 `"type": "module"` 删掉。这个问题的主要原因是 `ES Module` 的版本迭代对 `require` 支持变化的原因。
